import Head from "next/head";
import { useLanguageContext } from "../../contexts/LanguageContext";

export default function Home() {
	const { language } = useLanguageContext();
    
	return (
		<>
			<Head>
				<title>{language.generic.login}</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main></main>
		</>
	);
}
