import { Head, Html, Main, NextScript } from "next/document";

import { APP_CONFIG } from "../config/app-settings";

export default function Document() {
	return (
		<Html lang="en">
			<Head>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
				<script
					async
					src={APP_CONFIG.GOOGLE_ADDS.src}
					data-ad-client={APP_CONFIG.GOOGLE_ADDS.dataClient}
					slot={APP_CONFIG.GOOGLE_ADDS.slot}
					// crossorigin="anonymous"
					onError={console.error}
					crossOrigin="anonymous"
				/>
			</Head>
			<body>
				<Main />
				<NextScript />
			</body>
		</Html>
	);
}
